name: "Sphinx: Render docs"

on:
  release:
    types: [published]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      IS_TEST: True
    permissions:
      contents: write
    steps:
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    - uses: actions/checkout@v4
    - name: Install sphinx and build documentation with sphinx
      run: |
        python --version
        pip install sphinx sphinx_rtd_theme sphinxcontrib-email
        pip install pytest
        # try to install tkinter
        sudo apt install python3-tk
        pip install -e .
        echo Start testing...
        # run tests before building the documentation to set the environment variable IS_TEST
        pytest tests
        cd docs
        make html
#    - name: Build HTML
#      uses: ammaraskar/sphinx-action@master
#      with:
#        docs-folder: "docs/"
#        pre-build-command: "pip install sphinx_rtd_theme sphinxcontrib-email"
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: html-docs
        path: docs/build/html/
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      if: github.ref == 'refs/heads/main'
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: docs/build/html
